### PR TITLE
Add a rawBody property to req object in custom HTTP listeners

### PR DESCRIPTION
**Pull request by brodul**
Hello,

I modified the express middleware that is used in custom HTTP listeners (routers) so that a hubot user can access the actual body of the request as a string object. 

The need for this is described in #923 . It's probably impossible to access the unprocessed body without monkey-patching hubot itself.

I need this for validating github webhooks that use HMAC.
I added an example in the documentation how to do this.

Accessing the body in express 3.x and testing middlewares is hard. After trying different approaches I decided to implement this solution: http://stackoverflow.com/a/26634372/807339 .

Mocha has a hard time detecting assert errors inside routers in the test cases. Therefore I had to rethrow them in the test context/namespace.

### CODE REVIEW

**Comment by brodul** [comment]
The tests fail for node.js 0.8 but it seems as a travis env problem.
http://stackoverflow.com/questions/31025048/npm-doesnt-work-get-always-this-error-error-cannot-find-module-are-we-ther

https://travis-ci.org/github/hubot/jobs/82107102

**Comment by brodul** [comment]
HI,

here is some :cake: :smile:

**Comment by brodul** [comment]
@bkeepers If you are considering reviewing this PR, I can fix it.

**Comment by timkinnane** [comment]
@brodul, would updating express to v4 help you with this? Just linking to #1379 in case these are related. I know we had a similar issue with web-hook authentication that we hacked around but I think express v4 would have helped.

**Pull request closed without merging**
