### PR TITLE
feat(log): Replace log module with the pino module

### PR DESCRIPTION
**Pull request by joeyguerra**
@levenleven suggested replacing `log` with `pino`. So here's a PR so we can test it, compare to `log` and discuss.

#1616 #1492

### CODE REVIEW

**Comment by technicalpickles** [comment]
Is `log` deprecated? I didn't see it on the list on https://github.com/hubotio/hubot/issues/1605

**Comment by joeyguerra** [comment]
I didn't see a deprecation warning, but it's been a while since someone made a commit to the repo: https://github.com/medikoo/log.

I created separate a separate PR for updating `log` because it's a significant change. So I'm treating it as part of a feature release, separate from this upcoming one with just updating dependencies.

This particular PR (using `Pino` instead) is just to serve as a place to discuss either continue using the `log` module, or replace it with `Pino` so that we can have structured logging.

**Comment by joeyguerra** [comment]
@technicalpickles @xurizaemon @levenleven Ok ya'll. This PR replaces the logging module with Pino which has structured/ndjson logging output. Please review.

Note that I believe this is a major version bump. Let me know if you think otherwise.

**Comment by joh6nn** [comment]
I would agree that this is a major bump

**Comment by joeyguerra** [comment]
Just needs someone to approve.

**Comment by joeyguerra** [comment]
@xurizaemon do you have a few minutes to review this PR?

**Review by technicalpickles — APPROVED** [review]

**Pull request merged**
