### PR TITLE
end-to-end test for "yo hubot"

### PR DESCRIPTION
**Pull request by gr2m**
part of https://github.com/hubotio/evolution/pull/4

### CODE REVIEW

**Comment by technicalpickles** [comment]
Huh, something about the node 8 environment really isn't liking the scoped-http-client

**Comment by gr2m** [comment]
I’m looking into it

**Comment by gr2m** [comment]
npm install /path/to/hubot will create a symlink in npm 5+. As the `require(scriptName)` calls for app-specific scripts happen inside hubot, we have to set NODE_PATH so they can be found when `hubot` is symlinked into the hubot app created with the generator. Easy workaround, I’ll push an update shortly

**Comment by gr2m** [comment]
for the record, also had to change the order of `yo hubot` and `npm install $HUBOT_FOLDER` because `yo hubot` would delete the `node_modules` folder in `$HUBOT_FOLDER` 😮

**Comment by gr2m** [comment]
hmpf :( something’s still not working :/ investigating

**Comment by gr2m** [comment]
I can no longer reproduce the problem when running the `bin/e2e-test.sh` script locally. The difference is that on Travis `NODE_PATH` is undefined while it’s set correctly on my local machine, see https://travis-ci.org/hubotio/hubot/builds/247237160#L239

I guess there is some difference in how `expect` behaves differently between my mac and Debian on travis. I’m not sure how to work around this problem, I’d appreciate help from someone who is running linux locally and might have some experience with `expect` /cc @mose

**Comment by gr2m** [comment]
💚 💚 💚  I think this ready to merge now

**Pull request merged**
