### PR TITLE
chore(package): Updating and removing dependencies

### PR DESCRIPTION
**Pull request by joeyguerra**
I removed `chalk` since it was only used to make some text bold in the Shell Adapter. I don't think bolding was worth including all the `chalk` dependency surface area.

I also added tests for the Shell adapter since this touches that file.

#1605

### CODE REVIEW

**Comment by technicalpickles** [comment]
> I don't think bolding was worth including all the chalk dependency surface area.

The main reason for bold text is to make the shell more usable, because otherwise the text looks the same. I could see a case for choosing more than just bold.

Moving the adapter to its own repo could be another possibility.

**Comment by joeyguerra** [comment]
I think there's value in keeping the Shell in here and the default adapter so that I can use it right off the bat. But I'd rather have less dependencies the bold text for a scenario that is probably short term. As in I'm only using the default Shell adapter for a few minutes before wanting to either build my own, or use a different adapter.

**Comment by joeyguerra** [comment]
Btw, I was thinking that after merging this request, we could do another release. And then move onto updating the log module.

**Comment by technicalpickles** [comment]
> But I'd rather have less dependencies the bold text for a scenario that is probably short term. As in I'm only using the default Shell adapter for a few minutes before wanting to either build my own, or use a different adapter.

For what it is worth, I've always used the shell adapter when building out scripts initially, so it wasn't ever a 'short term' thing.

If you want to drop the dependency, I can understand that. I'd recommend coding our own bold then, it's just a matter of outputting the right escape codes, and then resetting them after. You could even look at the chalk implementation.

**Comment by joeyguerra** [comment]
> If you want to drop the dependency, I can understand that. I'd recommend coding our own bold then, it's just a matter of outputting the right escape codes, and then resetting them after. You could even look at the chalk implementation.

Done.

**Review by technicalpickles — APPROVED** [review]

**Comment by technicalpickles** [comment]
> Btw, I was thinking that after merging this request, we could do another release. And then move onto updating the log module.

Could you make an issue to track that? Just don't want to lose track. We should get semantic-release going too

**Comment by joeyguerra** [comment]
Yes. #1620

**Pull request merged**
