### PR TITLE
added robot.once function, wrapper for events.once

### PR DESCRIPTION
**Pull request by shokai**
I have added `robot.once` function.

[events.once](https://nodejs.org/api/events.html#events_emitter_once_event_listener) is useful for handling one time event.
It is available at [node v0.3.0](https://nodejs.org/docs/v0.3.0/api.html)

### CODE REVIEW

**Comment by michaelansel** [comment]
This looks good to me. @technicalpickles, do you think we should have test cases for simple wrappers like this? It seems unnecessary if we are just matching the underlying API.

**Comment by sdimkov** [comment]
+1 on this

**Comment by technicalpickles** [comment]
> A wrapper around the EventEmitter API to make usage semantically better.

As we add more of these, it makes me wonder if this is actually true. Is it any easier than using `robot.events.once`, `robots.events.on`, `robots.events.emit`, etc?

**Comment by technicalpickles** [comment]
I think the only thing this is missing is some docs in `docs/scripting.md` in the Events section.

**Comment by timkinnane** [comment]
Just pinging this issue because I don't think it's resolved as determined, re updating the docs. I also had wondered about the usage, because I tried using chai-eventemitter to test Robot events but it didn't work because of the missing once. Now I realise I could have tested `robot.events` - so I think some clarification in the docs would actually be useful.

**Pull request closed without merging**
