### PR TITLE
Evolution/4/javascript tests

### PR DESCRIPTION
**Pull request by PEPEInvest**

### CODE REVIEW

**Comment by guivinicius** [comment]
Looking good! 👍

**Comment by zaaraameera2014** [comment]
Google

**Comment by zaaraameera2014** [comment]
Peninglah

**Comment by brntbeer** [comment]
@PEPEInvest could you take a look at the conflicts and resolve those?

**Comment by zaaraameera2014** [comment]
0p

Pada Kha, 14 Jun 2018 9:56 PM Brent Beer <notifications@github.com> menulis:

**Pull request closed without merging**
