### PR TITLE
Bump express and connect-multiparty

### PR DESCRIPTION
**Pull request by mistydemeo**
These two dependencies were lagging behind the current published versions.

According to the [express migration guide](https://github.com/expressjs/express/wiki/Migrating-from-3.x-to-4.x), it doesn't look like Hubot hits any of the pain points there. The tests are also passing.

### CODE REVIEW

**Comment by mistydemeo** [comment]
Node 4 failure looks unrelated.

**Comment by mistydemeo** [comment]
Had the chance to test this with a production Hubot; it's responding to `GET` requests just fine.

**Comment by technicalpickles** [comment]
Chatted with @mistydemeo about this one. There are express changes, so we are figuring this is a minor version bump.

Other problem with releasing this is that 3.x is still marked as `next` (https://github.com/hubotio/hubot/issues/1406). I'm not sure where things were left off blocking it (https://github.com/hubotio/hubot/issues/1057), but I think it has been out this long that we should tag this release as `latest` and sort out the problems that happen.

**Comment by mistydemeo** [comment]
> There are express changes, so we are figuring this is a minor version bump.

👍 I'm figuring this should be 3.1.0 rather than 3.0.2.

**Comment by mistydemeo** [comment]
Can confirm the Node 4 failure is occurring on master, and was not introduced in this branch: https://travis-ci.org/hubotio/hubot/builds/411422293

**Pull request merged**
